# This is a GitHub action for building and publishing the docker image for 
# Azure Spring Apps hello world sample https://github.com/spring-guides/gs-spring-boot-for-azure

name: ASA Hello World Docker Image CI

on:
  workflow_dispatch:
    inputs:
      commit-sha:
        required: true
        description: The full (not short) commit SHA to check out and build from.
      tag:  
        required: true
        description: The Docker image tag, such as 0.0.1.
      dockerfile-path:
        required: false
        description: The Dockerfile to build the image.
        default: "https://raw.githubusercontent.com/Azure/spring-cloud-azure-tools/main/asa-sample-helloworld/Dockerfile"
    
env: 
  IMAGE_NAME: samples/hello-world
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with: 
        repository: 'spring-guides/gs-spring-boot-for-azure'
        ref: ${{ github.event.inputs.commit-sha }}
    - name: Setup Java JDK
      uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
      with:  
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
    - name: Download the Dockerfile
      run:  curl -L ${{ github.event.inputs.dockerfile-path }}  -o Dockerfile
      working-directory: ./complete 
    - name: Build with Maven
      run: ./mvnw clean package  
      working-directory: ./complete
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4.3.0
    - name: Log into registry
      uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
      with:
        registry: ${{ secrets.ACR_ENDPOINT }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}    
    - name: Build and push Docker images
      uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
      with:
        context: ./complete
        platforms: linux/amd64, linux/arm64
        push: true
        tags: ${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.tag }}
    
